name: GitHub Actions Demo MAIN Program
run-name: ${{ github.actor }} is testing out GitHub Actions MAIN Program
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
